kind: Deployment
apiVersion: apps/v1
metadata:
  name: test-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
        - name: test-app
          image: microaditi/test:latest
          ports:
            - containerPort: 5000
